### PR TITLE
Completed test for ServeError with nil Error, as discussed in #13

### LINKED ISSUE #13: Question: ServeError type switch
I am wondering how we may produce a testcase to enter this type type switch branch here:
https://github.com/go-openapi/errors/blob/7bcb96a367bac6b76e6e42fa84155bb5581dcff8/api.go#L128

I assume the intent is to detect a nil pointer on a type implementing the Error interface{}, but it looks like things don't work that way...

In my opinion, really guarding against nil here would involve some reflection, with something like:
reflect.ValueOf(e).IsNil() when reflect.TypeOf(e) is a nillable type...

I did not feel like polluting the code with reflection so I gave up. But the question is still itching...
Similar type switches do exist in the validate package, which I consistently failed to explore with valid test cases...

Please advise.

### PR DESCRIPTION
**Pull request by fredbi**
Fixes #13

Added golangci and go report card badges

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

File: api_test.go [hunk 1]
```diff
@@ -23,6 +23,11 @@ import (
 	"github.com/stretchr/testify/assert"
 )
 
+type customError struct {
+	apiError
+	dummy string
```
Comment (golangcibot) [inline api_test.go]: `dummy` is unused
